Repository MBRzealand/NewYorker, pull requests merged in 2021-06, with the labels that each got.

#154 Update AD to include exceptions / Error check
  02 Requiements/ADs/ADMainScenario.pdf
  02 Requiements/ADs/ADMainScenario.vsdx
  02 Requiements/ADs/ADMainScenarioWthErrorChecks.pdf
  02 Requiements/ADs/ADMainScenarioWthErrorChecks.vsdx
Labels: enhancement

#160 Update usecase1(brief) to accommodate iteration3
  02 Requiements/UseCases/UseCase1SendRequest(Brief).md
Labels: documentation, enhancement

#161 Update usecase1(casual) to accommodate iteration3
  02 Requiements/UseCases/UseCase1SendRequest(Casual).md
Labels: documentation, enhancement

#165 Create prototype1
  04 Implementation/.idea/jarRepositories.xml
  04 Implementation/.idea/runConfigurations.xml
  04 Implementation/app/build.gradle
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/SendRequestActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/CustomerAddressContainsSpecialCharacterException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/CustomerEmailAddressWithoutAtSignException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/CustomerEmailAddressWithoutPeriodException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/CustomerNameNumericException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/CustomerPhoneNumberNotNumericException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/CustomerZIPCodeNotFourDigitsException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/CustomerZIPCodeNotNumericException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingChosenStoreException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingCustomerAddressException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingCustomerEmailAddressException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingCustomerNameException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingCustomerPhoneNumberException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingCustomerZIPCodeException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingWallHeightException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/MissingWallWidthException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/WallHeightNotNumericException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/WallHeightTooHighException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/WallHeightTooSmallException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/WallWidthNotNumericException.java
  04 Implementation/app/src/main/java/com/example/newyorker/exceptions/WallWidthTooSmallException.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Customer.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Observer.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Specifications.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity__send__request.xml
  04 Implementation/app/src/main/res/layout-v21/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
  04 Implementation/app/src/main/res/layout-v21/activity_preview_order.xml
  04 Implementation/app/src/main/res/layout/activity__send__request.xml
  04 Implementation/app/src/main/res/layout/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/layout/activity_preview_order.xml
  04 Implementation/app/src/main/res/values/strings.xml
Labels: documentation, enhancement

#162 Update usecase1(fully dressed)to accommodate iteration3
  02 Requiements/UseCases/UseCase1SendRequest(Fully).md
Labels: documentation, enhancement

#163 Update ssd to accommodate iteration3
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
  02 Requiements/SSDs/SSDMainScenarioWithCustomizations.pdf
  02 Requiements/SSDs/SSDMainScenarioWithCustomizations.vsdx
Labels: documentation, enhancement

#173 Updated a method to correctly check from errors
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
Labels: enhancement

#171 Update modules
  04 Implementation/.idea/compiler.xml
  04 Implementation/.idea/jarRepositories.xml
  04 Implementation/.idea/misc.xml
  04 Implementation/app/build.gradle
  04 Implementation/build.gradle
Labels: documentation

#176 Add notes to customer class
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Customer.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Specifications.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
Labels: enhancement

#169 UpdateAdToAccommodateIteration3Changes
  02 Requiements/ADs/ADMainScenarioWithCustomization.pdf
  02 Requiements/ADs/ADMainScenarioWithCustomization.vsdx
  02 Requiements/ADs/ADMainScenarioWthErrorChecks.pdf
  02 Requiements/ADs/ADMainScenarioWthErrorChecks.vsdx
Labels: documentation

#180 Update OC to accommodate Iteration3 customize request
  03 Design/OCs/OCGetDoors.md
  03 Design/OCs/OCGetHandles.md
  03 Design/OCs/OCGetSpecialGlass.md
  03 Design/OCs/OCGetStores.md
  03 Design/OCs/OCSetDoor.md
  03 Design/OCs/OCSetHandle.md
  03 Design/OCs/OCSetSpecialGlass.md
  03 Design/OCs/OCSetStore.md
Labels: documentation, enhancement

#182 Make checkboxes and spinners uninteractable when they aren't needed
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_customize_order.xml
Labels: documentation

#185 fixed the controller to have a name in all SD's
  03 Design/SDs/SDCalculateTotalPrice.pdf
  03 Design/SDs/SDCalculateTotalPrice.vsdx
  03 Design/SDs/SDCalculateWallPrice.pdf
  03 Design/SDs/SDCalculateWallPrice.vsdx
  03 Design/SDs/SDGetStores.pdf
  03 Design/SDs/SDGetStores.vsdx
  03 Design/SDs/SDSetCustomerAddress.pdf
  03 Design/SDs/SDSetCustomerAddress.vsdx
  03 Design/SDs/SDSetCustomerEmailAddress.pdf
  03 Design/SDs/SDSetCustomerEmailAddress.vsdx
  03 Design/SDs/SDSetCustomerName.pdf
  03 Design/SDs/SDSetCustomerName.vsdx
  03 Design/SDs/SDSetCustomerPhoneNumber.pdf
  03 Design/SDs/SDSetCustomerPhoneNumber.vsdx
  03 Design/SDs/SDSetCustomerZIPCode.pdf
  03 Design/SDs/SDSetCustomerZIPCode.vsdx
  03 Design/SDs/SDSetStore.pdf
  03 Design/SDs/SDSetStore.vsdx
  03 Design/SDs/SDSetWallHeight.pdf
  03 Design/SDs/SDSetWallHeight.vsdx
  03 Design/SDs/SDSetWallWidth.pdf
  03 Design/SDs/SDSetWallWidth.vsdx
  03 Design/SDs/SDnotifyObservers.pdf
  03 Design/SDs/SDnotifyObservers.vsdx
Labels: documentation, enhancement

#190 Updated Observer on SD's
  03 Design/SDs/SDCalculateTotalPrice.pdf
  03 Design/SDs/SDCalculateTotalPrice.vsdx
  03 Design/SDs/SDCalculateWallPrice.pdf
  03 Design/SDs/SDCalculateWallPrice.vsdx
  03 Design/SDs/SDSetCustomerAddress.pdf
  03 Design/SDs/SDSetCustomerAddress.vsdx
  03 Design/SDs/SDSetCustomerEmailAddress.pdf
  03 Design/SDs/SDSetCustomerEmailAddress.vsdx
  03 Design/SDs/SDSetCustomerName.pdf
  03 Design/SDs/SDSetCustomerName.vsdx
  03 Design/SDs/SDSetCustomerPhoneNumber.pdf
  03 Design/SDs/SDSetCustomerPhoneNumber.vsdx
  03 Design/SDs/SDSetCustomerZIPCode.pdf
  03 Design/SDs/SDSetCustomerZIPCode.vsdx
  03 Design/SDs/SDSetStore.pdf
  03 Design/SDs/SDSetStore.vsdx
  03 Design/SDs/SDSetWallHeight.pdf
  03 Design/SDs/SDSetWallHeight.vsdx
  03 Design/SDs/SDSetWallWidth.pdf
  03 Design/SDs/SDSetWallWidth.vsdx
Labels: documentation, enhancement

#191 Update Project Plan
  08 Project Management/ProjectPlan.md
Labels: documentation

#192 Updated update DCDToAccomodateiteration3customizeRequest from master
  03 Design/SDs/SDCalculateTotalPrice.pdf
  03 Design/SDs/SDCalculateTotalPrice.vsdx
  03 Design/SDs/SDCalculateWallPrice.pdf
  03 Design/SDs/SDCalculateWallPrice.vsdx
  03 Design/SDs/SDSetCustomerAddress.pdf
  03 Design/SDs/SDSetCustomerAddress.vsdx
  03 Design/SDs/SDSetCustomerEmailAddress.pdf
  03 Design/SDs/SDSetCustomerEmailAddress.vsdx
  03 Design/SDs/SDSetCustomerName.pdf
  03 Design/SDs/SDSetCustomerName.vsdx
  03 Design/SDs/SDSetCustomerPhoneNumber.pdf
  03 Design/SDs/SDSetCustomerPhoneNumber.vsdx
  03 Design/SDs/SDSetCustomerZIPCode.pdf
  03 Design/SDs/SDSetCustomerZIPCode.vsdx
  03 Design/SDs/SDSetStore.pdf
  03 Design/SDs/SDSetStore.vsdx
  03 Design/SDs/SDSetWallHeight.pdf
  03 Design/SDs/SDSetWallHeight.vsdx
  03 Design/SDs/SDSetWallWidth.pdf
  03 Design/SDs/SDSetWallWidth.vsdx
  08 Project Management/ProjectPlan.md
Labels: documentation, enhancement

#188 Update DCD to accommodateiteration3customize request
  03 Design/DCDMainScenario.pdf
  03 Design/DCDMainScenario.vsdx
  03 Design/DCDs/DCDMainScenario.pdf
  03 Design/DCDs/DCDMainScenario.vsdx
Labels: enhancement

#193 Updated addSDsForIteration3 from master
  03 Design/DCDMainScenario.pdf
  03 Design/DCDMainScenario.vsdx
  03 Design/DCDs/DCDMainScenario.pdf
  03 Design/DCDs/DCDMainScenario.vsdx
  03 Design/SDs/SDCalculateTotalPrice.pdf
  03 Design/SDs/SDCalculateTotalPrice.vsdx
  03 Design/SDs/SDCalculateWallPrice.pdf
  03 Design/SDs/SDCalculateWallPrice.vsdx
  03 Design/SDs/SDSetCustomerAddress.pdf
  03 Design/SDs/SDSetCustomerAddress.vsdx
  03 Design/SDs/SDSetCustomerEmailAddress.pdf
  03 Design/SDs/SDSetCustomerEmailAddress.vsdx
  03 Design/SDs/SDSetCustomerName.pdf
  03 Design/SDs/SDSetCustomerName.vsdx
  03 Design/SDs/SDSetCustomerPhoneNumber.pdf
  03 Design/SDs/SDSetCustomerPhoneNumber.vsdx
  03 Design/SDs/SDSetCustomerZIPCode.pdf
  03 Design/SDs/SDSetCustomerZIPCode.vsdx
  03 Design/SDs/SDSetStore.pdf
  03 Design/SDs/SDSetStore.vsdx
  03 Design/SDs/SDSetWallHeight.pdf
  03 Design/SDs/SDSetWallHeight.vsdx
  03 Design/SDs/SDSetWallWidth.pdf
  03 Design/SDs/SDSetWallWidth.vsdx
  08 Project Management/ProjectPlan.md
Labels: documentation, enhancement

#187 Add sds for iteration3
  03 Design/SDs/SDGetDoors.pdf
  03 Design/SDs/SDGetDoors.vsdx
  03 Design/SDs/SDGetSpecialGlass.pdf
  03 Design/SDs/SDGetSpecialGlass.vsdx
  03 Design/SDs/SDGethandles.pdf
  03 Design/SDs/SDGethandles.vsdx
  03 Design/SDs/SDSetDoor.pdf
  03 Design/SDs/SDSetDoor.vsdx
  03 Design/SDs/SDSetHandle.pdf
  03 Design/SDs/SDSetHandle.vsdx
  03 Design/SDs/SDSetSpecialGlass.pdf
  03 Design/SDs/SDSetSpecialGlass.vsdx
Labels: documentation

#201 Made widthInput force close keyboard on "done" button click
  04 Implementation/.idea/.name
  04 Implementation/.idea/misc.xml
  04 Implementation/app/build.gradle
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
Labels: enhancement

#203 Create espresso tests
  04 Implementation/.idea/misc.xml
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_01.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_02.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_03.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_04.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_05.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_06.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_07.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_08.java
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
Labels: enhancement

#204 Updated addCustomizationVariables from master
  04 Implementation/.idea/.name
  04 Implementation/app/build.gradle
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_01.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_02.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_03.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_04.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_05.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_06.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_07.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_08.java
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
Labels: enhancement

#195 Added the static variables for customization options
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
Labels: enhancement

#206 Changed Email intent construction
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
Labels: documentation

#209 Fix emailling issues for android11 and android 10
  04 Implementation/app/src/main/java/com/example/newyorker/view/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
Labels: enhancement

#210 Updated createTestcases from master
  04 Implementation/app/src/main/java/com/example/newyorker/view/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
Labels: documentation, enhancement

#214 Updated ImplementCalculationOfPanelWidthAndHeightAsWellAsPanelCount from updateCustomizeMethod
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/res/values/strings.xml
Labels: enhancement

#215 Updated updateCustomizeMethod from ImplementCalculationOfPanelWidthAndHeightAsWellAsPanelCount
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
Labels: enhancement

#217 Moved DOM to 01 Business Modelling and fixed small mistakes
  01 Business Modeling/DOMs/,
  01 Business Modeling/DOMs/DOMMainScenarioWithCustomazations.pdf
  01 Business Modeling/DOMs/DOMMainScenarioWithCustomazations.vsdx
  02 Requirements/ADs/ADMainScenarioWithCustomization.pdf
  02 Requirements/ADs/ADMainScenarioWithCustomization.vsdx
  02 Requirements/FURPSPlus.md
  02 Requirements/SSDs/SSDMainScenarioWithCustomizations.pdf
  02 Requirements/SSDs/SSDMainScenarioWithCustomizations.vsdx
  02 Requirements/UCDs/UseCaseDiagram.pdf
  02 Requirements/UCDs/UseCaseDiagram.vsdx
  02 Requirements/UCs/UseCase1SendRequest(Brief).md
  02 Requirements/UCs/UseCase1SendRequest(Casual).md
  02 Requirements/UCs/UseCase1SendRequest(Fully).md
Labels: enhancement

#219 Update customize method
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_01.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_02.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_03.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_04.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_05.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_06.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_07.java
  04 Implementation/app/src/androidTest/java/com/example/newyorker/view/Espresso_Test_08.java
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/values/strings.xml
Labels: enhancement

#213 Create testcases
  05 Test/,
  05 Test/EspressoTest.md
  05 Test/UnitTest.md
Labels: documentation

#222 Add splash screen to application
  04 Implementation/.idea/misc.xml
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/view/Splashscreen.java
  04 Implementation/app/src/main/res/layout-v21/activity_splashscreen.xml
Labels: enhancement

#229 Update email feature so it now works in the background
  04 Implementation/app/build.gradle
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/model/Customer.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/Splashscreen.java
  04 Implementation/build.gradle
Labels: enhancement

#230 Fix small requested errors
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_format_list_bulleted_24.xml
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_local_phone_24.xml
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_menu_book_24.xml
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_shopping_cart_24.xml
  04 Implementation/app/src/main/res/drawable/ic_baseline_info_24.xml
  04 Implementation/app/src/main/res/drawable/ic_baseline_menu_24.xml
  04 Implementation/app/src/main/res/layout-v21/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout/activity_customize_order.xml
  04 Implementation/app/src/main/res/menu/my_menu.xml
  04 Implementation/app/src/main/res/values/strings.xml
  04 Implementation/app/src/main/res/values/themes.xml
Labels: enhancement

#231 Update addCreateMultipleWallsFeature branch with master branch
  04 Implementation/app/build.gradle
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Customer.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/Splashscreen.java
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_format_list_bulleted_24.xml
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_local_phone_24.xml
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_menu_book_24.xml
  04 Implementation/app/src/main/res/drawable-v24/ic_baseline_shopping_cart_24.xml
  04 Implementation/app/src/main/res/drawable/ic_baseline_info_24.xml
  04 Implementation/app/src/main/res/drawable/ic_baseline_menu_24.xml
  04 Implementation/app/src/main/res/layout-v21/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout/activity_customize_order.xml
  04 Implementation/app/src/main/res/menu/my_menu.xml
  04 Implementation/app/src/main/res/values/strings.xml
  04 Implementation/app/src/main/res/values/themes.xml
  04 Implementation/build.gradle
Labels: enhancement

#233 Remove old lockbox features
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
Labels: bug, enhancement

#235 Added Catalogue Feature
  04 Implementation/.idea/misc.xml
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_catalogue.xml
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/dobbeltdoer_m_12_glas.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/dobbeltdoer_m_12_glas_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/doer_m_6_glas.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/doer_m_6_glas_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/et_fag_m_4_glas.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/et_fag_m_4_glas_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/fem_fag_m_20_glas_m_enkeltdoer.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/fem_fag_m_20_glas_m_enkeltdoer_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/fire_fag_m_16_glas_m_dobbeltdoer.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/fire_fag_m_16_glas_m_dobbeltdoer_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/seks_fag_m_24_glas_m_enkeltdoer.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/seks_fag_m_24_glas_m_enkeltdoer_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/skydedoer_m_6_glas.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/skydedoer_m_6_glas_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/to_fag_m_6_glas.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/to_fag_m_6_glas_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/to_fag_m_8_glas.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/to_fag_m_8_glas_highlighted.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/tre_fag_m_12_glas_m_enkeltdoer.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/tre_fag_m_12_glas_m_enkeltdoer_highlighted.png
  04 Implementation/app/src/main/res/values/colors.xml
Labels: enhancement

#236 Updated catalogue to match index for door types
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
Labels: enhancement

#241 updated addWallNamingFeature from master
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
Labels: enhancement

#242 Add Wall Naming Feature
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
Labels: enhancement

#243 Updated addContactPage from master
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
Labels: enhancement

#244 Update addStartMenu from master
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/ContactActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  04 Implementation/app/src/main/res/layout-v21/activity_contact.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
  04 Implementation/app/src/main/res/menu/webviewtoolbar.xml
  04 Implementation/app/src/main/res/values/strings.xml
Labels: enhancement

#245 Add Start Menu
  04 Implementation/.idea/misc.xml
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainMenu.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/Splashscreen.java
  04 Implementation/app/src/main/res/drawable-widecg/shutter_s.png
  04 Implementation/app/src/main/res/layout-v21/activity_main_menu.xml
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/facebook.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/instagram.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/linkedin.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/pintrest.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/twitter.png
Labels: enhancement

#246 Merge master into addBasketFeature branch
  04 Implementation/.idea/misc.xml
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/ContactActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainMenu.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/Splashscreen.java
  04 Implementation/app/src/main/res/drawable-widecg/shutter_s.png
  04 Implementation/app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  04 Implementation/app/src/main/res/layout-v21/activity_contact.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main_menu.xml
  04 Implementation/app/src/main/res/menu/webviewtoolbar.xml
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/facebook.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/instagram.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/linkedin.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/pintrest.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/twitter.png
  04 Implementation/app/src/main/res/values/strings.xml
Labels: enhancement

#248 Add Start Menu
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/ContactActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainMenu.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main_menu.xml
Labels: enhancement

#249 updated addBasketFeature from master
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/ContactActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainMenu.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_main_menu.xml
Labels: enhancement

#250 Add Basket Feature
  04 Implementation/.idea/misc.xml
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/controller/NYBuilderController.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Email.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Specifications.java
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CatalogueActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/MainMenu.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/view/SendRequestActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity__send__request.xml
  04 Implementation/app/src/main/res/layout-v21/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main_menu.xml
  04 Implementation/app/src/main/res/layout-v21/activity_preview_order.xml
  04 Implementation/app/src/main/res/layout/activity_preview_order.xml
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/background.png
  04 Implementation/app/src/main/res/values/colors.xml
  04 Implementation/app/src/main/res/values/strings.xml
Labels: bug, enhancement

#251 merging all test branches into one
  04 Implementation/app/src/main/java/com/example/newyorker/model/Wall.java
  04 Implementation/app/src/test/java/com/example/newyorker/model/WallUnitTest.java
Labels: enhancement

#252 merging all test branches into one
  04 Implementation/app/src/main/java/com/example/newyorker/model/Specifications.java
  04 Implementation/app/src/test/java/com/example/newyorker/model/SpecificationsTest.java
  04 Implementation/app/src/test/java/com/example/newyorker/model/Wall.java
Labels: enhancement
