Repository MBRzealand/NewYorker, pull requests merged in 2021-05, with the labels that each got.

#17 Create project structur Folders
  01 Business Modeling/,
  02 Requiements/,
  03 Design/,
  05 Test/,
  06 Deployment/,
  07 Configuration & CM/,
  08 Project Management/,
  09 Environment/,
Labels: documentation

#18 Create time registering template
  08 Project Management/TimeRegistering/TimeRegisteringTemplate.md
Labels: documentation

#21 Create README.md
  README.md
Labels: documentation

#25 Create ProcedureForBranches.md
  09 Environment/ProcedureForBranches.md
Labels: documentation

#22 Create ProcedureForIssues.md
  09 Environment/ProcedureForIssues.md
Labels: documentation

#24 Create the Procedure for merging pull request
  09 Environment/MergeProcedure.md
Labels: documentation

#27 Updating risk analysis from master
  09 Environment/MergeProcedure.md
  09 Environment/ProcedureForBranches.md
  09 Environment/ProcedureForIssues.md
Labels: enhancement

#23 Create a risk analysis plan
  09 Environment/RiskAnalysis.md
Labels: documentation

#29 Added use case diagram
  02 Requiements/UseCaseDiagram/UseCaseDiagram.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagramImage.PNG
Labels: documentation

#54 Create first iteration of project plan
  08 Project Management/,
  08 Project Management/ProjectPlan.md
Labels: documentation

#58 Rename dealer in ucd
  02 Requiements/UseCaseDiagram/UseCaseDiagram.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagramImage.PNG
Labels: documentation, enhancement

#60 Updating briefUC1 from Master
  02 Requiements/UseCaseDiagram/UseCaseDiagram.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagramImage.PNG
Labels: enhancement

#61 Renamed Dealer in UC1
  02 Requiements/UseCases/UseCase1/BriefUC1.md
  02 Requiements/UseCases/UseCase2/placeholder.txt
  02 Requiements/UseCases/UseCase3/placeholder.txt
  02 Requiements/UseCases/UseCase4/placeholder.txt
Labels: documentation, enhancement

#63 Create brief UC2
  02 Requiements/,
  02 Requiements/UseCases/UseCase1/BriefUC1.md
  02 Requiements/UseCases/UseCase2/BriefUC2.md
  02 Requiements/UseCases/UseCase2/placeholder.txt
Labels: documentation

#62 Create CasualUC1.md
  02 Requiements/UseCases/UseCase1/CasualUC1.md
Labels: documentation

#66 Replace "prompts" with "presents" in all UC's
  .idea/gradle.xml
  02 Requiements/UseCases/UseCase1 - CreateOrder/BriefUC1CreateOrder.md
  02 Requiements/UseCases/UseCase1 - CreateOrder/CasualUC1CreateOrder.md
  02 Requiements/UseCases/UseCase2 - CustomizeOrder/BriefUC2CustomizeOrder.md
  02 Requiements/UseCases/UseCase2 - CustomizeOrder/CasualUC2CustomizeOrder.md
  02 Requiements/UseCases/UseCase3 - PreviewOrder/placeholder.txt
  02 Requiements/UseCases/UseCase4 - SendOrder/placeholder.txt
Labels: documentation, enhancement

#70 Fixed a small error with android.
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle
Labels: bug

#68 Update RiskAnalysis
  09 Environment/RiskAnalysis.md
Labels: documentation, enhancement

#69 Add mock up link
  03 Design/,
  03 Design/MockUpLink.md
Labels: documentation, enhancement

#73 Update and rename VisionDocument.md to InterestAnalysis.md
  01 Business Modeling/InterestAnalysis.md
  01 Business Modeling/VisionDocument.md
Labels: documentation

#85 moved all android related files into 04 Implementation
  04 Implementation/,
  04 Implementation/.gitignore
  04 Implementation/.idea/.gitignore
  04 Implementation/.idea/compiler.xml
  04 Implementation/.idea/gradle.xml
  04 Implementation/.idea/jarRepositories.xml
  04 Implementation/.idea/misc.xml
  04 Implementation/.idea/vcs.xml
  04 Implementation/app/.gitignore
  04 Implementation/app/build.gradle
  04 Implementation/app/proguard-rules.pro
  04 Implementation/app/src/androidTest/java/com/example/newyorker/ExampleInstrumentedTest.java
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/MainActivity.java
  04 Implementation/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  04 Implementation/app/src/main/res/drawable/ic_launcher_background.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/values-night/themes.xml
  04 Implementation/app/src/main/res/values/colors.xml
  04 Implementation/app/src/main/res/values/strings.xml
  04 Implementation/app/src/main/res/values/themes.xml
  04 Implementation/app/src/test/java/com/example/newyorker/ExampleUnitTest.java
  04 Implementation/build.gradle
  04 Implementation/gradle.properties
  04 Implementation/gradle/wrapper/gradle-wrapper.jar
  04 Implementation/gradle/wrapper/gradle-wrapper.properties
  04 Implementation/gradlew
  04 Implementation/gradlew.bat
  04 Implementation/settings.gradle
Labels: bug, enhancement

#88 Create procedure for implementation
  09 Environment/,
  09 Environment/ProcedureForImplementation.md
Labels: documentation, enhancement

#91 Updating combineUC1UC2UC3AndUC4 Branch from master
  09 Environment/,
  09 Environment/ProcedureForImplementation.md
Labels: enhancement

#90 Combine UC1, UC2, UC3 and UC4
  01 Business Modeling/,
  02 Requiements/UseCaseDiagram/UseCaseDiagram.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagramImage.PNG
  02 Requiements/UseCaseDiagram/UseCaseDiagramPicture.PNG
  02 Requiements/UseCases/TmpBriefUC.md
  02 Requiements/UseCases/TmpCasualUC.md
  02 Requiements/UseCases/UseCase1 - CreateOrder/BriefUC1CreateOrder.md
  02 Requiements/UseCases/UseCase1 - CreateOrder/CasualUC1CreateOrder.md
  02 Requiements/UseCases/UseCase1SendRequest.md
  02 Requiements/UseCases/UseCase3 - PreviewOrder/placeholder.txt
  02 Requiements/UseCases/UseCase4 - SendOrder/placeholder.txt
Labels: documentation, enhancement

#93 Updating createSystemVision from master branch
  01 Business Modeling/,
  02 Requiements/UseCaseDiagram/UseCaseDiagram.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagramImage.PNG
  02 Requiements/UseCaseDiagram/UseCaseDiagramPicture.PNG
  02 Requiements/UseCases/TmpBriefUC.md
  02 Requiements/UseCases/TmpCasualUC.md
  02 Requiements/UseCases/UseCase1 - CreateOrder/BriefUC1CreateOrder.md
  02 Requiements/UseCases/UseCase1 - CreateOrder/CasualUC1CreateOrder.md
  02 Requiements/UseCases/UseCase1SendRequest.md
  02 Requiements/UseCases/UseCase3 - PreviewOrder/placeholder.txt
  02 Requiements/UseCases/UseCase4 - SendOrder/placeholder.txt
  04 Implementation/,
  04 Implementation/.gitignore
  04 Implementation/.idea/.gitignore
  04 Implementation/.idea/compiler.xml
  04 Implementation/.idea/gradle.xml
  04 Implementation/.idea/jarRepositories.xml
  04 Implementation/.idea/misc.xml
  04 Implementation/.idea/vcs.xml
  04 Implementation/app/.gitignore
  04 Implementation/app/build.gradle
  04 Implementation/app/proguard-rules.pro
  04 Implementation/app/src/androidTest/java/com/example/newyorker/ExampleInstrumentedTest.java
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/MainActivity.java
  04 Implementation/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  04 Implementation/app/src/main/res/drawable/ic_launcher_background.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/values-night/themes.xml
  04 Implementation/app/src/main/res/values/colors.xml
  04 Implementation/app/src/main/res/values/strings.xml
  04 Implementation/app/src/main/res/values/themes.xml
  04 Implementation/app/src/test/java/com/example/newyorker/ExampleUnitTest.java
  04 Implementation/build.gradle
  04 Implementation/gradle.properties
  04 Implementation/gradle/wrapper/gradle-wrapper.jar
  04 Implementation/gradle/wrapper/gradle-wrapper.properties
  04 Implementation/gradlew
  04 Implementation/gradlew.bat
  04 Implementation/settings.gradle
  09 Environment/,
  09 Environment/ProcedureForImplementation.md
Labels: enhancement

#80 Update and rename InterestAnalysis.md to VisionDocument.md
  01 Business Modeling/InterestAnalysis.md
  01 Business Modeling/VisionDocument.md
Labels: documentation

#94 Updating createFURPS+Document from master
  01 Business Modeling/,
  01 Business Modeling/VisionDocument.md
  02 Requiements/UseCaseDiagram/UseCaseDiagram.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagramImage.PNG
  02 Requiements/UseCaseDiagram/UseCaseDiagramPicture.PNG
  02 Requiements/UseCases/TmpBriefUC.md
  02 Requiements/UseCases/TmpCasualUC.md
  02 Requiements/UseCases/UseCase1 - CreateOrder/BriefUC1CreateOrder.md
  02 Requiements/UseCases/UseCase1 - CreateOrder/CasualUC1CreateOrder.md
  02 Requiements/UseCases/UseCase1SendRequest.md
  02 Requiements/UseCases/UseCase3 - PreviewOrder/placeholder.txt
  02 Requiements/UseCases/UseCase4 - SendOrder/placeholder.txt
  04 Implementation/,
  04 Implementation/.gitignore
  04 Implementation/.idea/.gitignore
  04 Implementation/.idea/compiler.xml
  04 Implementation/.idea/gradle.xml
  04 Implementation/.idea/jarRepositories.xml
  04 Implementation/.idea/misc.xml
  04 Implementation/.idea/vcs.xml
  04 Implementation/app/.gitignore
  04 Implementation/app/build.gradle
  04 Implementation/app/proguard-rules.pro
  04 Implementation/app/src/androidTest/java/com/example/newyorker/ExampleInstrumentedTest.java
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/MainActivity.java
  04 Implementation/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  04 Implementation/app/src/main/res/drawable/ic_launcher_background.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  04 Implementation/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  04 Implementation/app/src/main/res/values-night/themes.xml
  04 Implementation/app/src/main/res/values/colors.xml
  04 Implementation/app/src/main/res/values/strings.xml
  04 Implementation/app/src/main/res/values/themes.xml
  04 Implementation/app/src/test/java/com/example/newyorker/ExampleUnitTest.java
  04 Implementation/build.gradle
  04 Implementation/gradle.properties
  04 Implementation/gradle/wrapper/gradle-wrapper.jar
  04 Implementation/gradle/wrapper/gradle-wrapper.properties
  04 Implementation/gradlew
  04 Implementation/gradlew.bat
  04 Implementation/settings.gradle
  08 Project Management/TimeRegistering/Lasse J. Kongsdal.md
  09 Environment/,
  09 Environment/ProcedureForImplementation.md
Labels: enhancement

#95 Create combined casual UC1
  02 Requiements/UseCases/UseCase1SendRequest(Brief).md
  02 Requiements/UseCases/UseCase1SendRequest(Casual).md
Labels: documentation, enhancement

#97 Create disposition
  08 Project Management/Disposition.md
  README.md
Labels: documentation, enhancement

#101 Updated FURPS+Document from master
  02 Requiements/UseCases/UseCase1SendRequest(Brief).md
  02 Requiements/UseCases/UseCase1SendRequest(Casual).md
  08 Project Management/Disposition.md
  README.md
Labels: enhancement

#74 Create FURPSPlus
  02 Requiements/FURPSPlus.md
Labels: documentation

#102 update reviseRiskAnalysis from master
  02 Requiements/FURPSPlus.md
Labels: enhancement

#99 Revise Risk Analysis
  08 Project Management/RiskAnalysis.md
  09 Environment/RiskAnalysis.md
Labels: documentation, enhancement

#103 Updated createUseCase1FullyDressed from master
  02 Requiements/FURPSPlus.md
  08 Project Management/RiskAnalysis.md
  09 Environment/RiskAnalysis.md
Labels: enhancement

#100 Create use case1 fully dressed
  02 Requiements/UseCases/UseCase1SendRequest(Fully).md
Labels: documentation

#104 Remove tmpBriefUC and tmpCasualUC
  02 Requiements/UseCases/TmpBriefUC.md
  02 Requiements/UseCases/TmpCasualUC.md
Labels: documentation, duplicate

#105 Create SSD1
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagram.pdf
  02 Requiements/UseCaseDiagram/UseCaseDiagramPicture.PNG
Labels: documentation

#106 Updated updateUC1BasedOnSSDWorkFlow from master
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
  02 Requiements/UseCaseDiagram/UseCaseDiagram.pdf
  02 Requiements/UseCaseDiagram/UseCaseDiagramPicture.PNG
Labels: enhancement

#108 Created AD for the main scenario
  02 Requiements/ADs/ADMainScenario.pdf
  02 Requiements/ADs/ADMainScenario.vsdx
Labels: documentation

#109 Updated updateUC1BasedOnSSDWorkFlow from master
  02 Requiements/ADs/ADMainScenario.pdf
  02 Requiements/ADs/ADMainScenario.vsdx
Labels: enhancement

#111 Update AD1 main scenario
  02 Requiements/ADs/ADMainScenario.pdf
  02 Requiements/ADs/ADMainScenario.vsdx
Labels: documentation

#107 Update uc1 based on ssd work flow
  02 Requiements/UseCases/UseCase1SendRequest(Fully).md
Labels: documentation

#113 Update SSD
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
Labels: documentation, enhancement

#117 Update SSDMainScenario
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
Labels: documentation, enhancement

#123 Updated SSD to contain error checks
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
Labels: documentation, enhancement

#126 Updated updateSDs from master
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
Labels: enhancement

#124 Update SDs to include observer patterns
  03 Design/SDs/SDCalculateTotalPrice.pdf
  03 Design/SDs/SDCalculateTotalPrice.vsdx
  03 Design/SDs/SDCalculateWallPrice.pdf
  03 Design/SDs/SDCalculateWallPrice.vsdx
  03 Design/SDs/SDGetStores.pdf
  03 Design/SDs/SDGetStores.vsdx
  03 Design/SDs/SDSetCustomerAddress.pdf
  03 Design/SDs/SDSetCustomerAddress.vsdx
  03 Design/SDs/SDSetCustomerEmailAddress.pdf
  03 Design/SDs/SDSetCustomerEmailAddress.vsdx
  03 Design/SDs/SDSetCustomerName.pdf
  03 Design/SDs/SDSetCustomerName.vsdx
  03 Design/SDs/SDSetCustomerPhoneNumber.pdf
  03 Design/SDs/SDSetCustomerPhoneNumber.vsdx
  03 Design/SDs/SDSetCustomerZIPCode.pdf
  03 Design/SDs/SDSetCustomerZIPCode.vsdx
  03 Design/SDs/SDSetStore.pdf
  03 Design/SDs/SDSetStore.vsdx
  03 Design/SDs/SDSetWallHeight.pdf
  03 Design/SDs/SDSetWallHeight.vsdx
  03 Design/SDs/SDSetWallWidth.pdf
  03 Design/SDs/SDSetWallWidth.vsdx
  03 Design/SDs/SDnotifyObservers.pdf
  03 Design/SDs/SDnotifyObservers.vsdx
Labels: documentation

#127 Updated createOCsForUC1 from master
  02 Requiements/DOMs/,
  02 Requiements/DOMs/DOMMainScenario.pdf
  02 Requiements/DOMs/DOMMainScenario.vsdx
  02 Requiements/SSDs/SSDMainScenario.pdf
  02 Requiements/SSDs/SSDMainScenario.vsdx
  03 Design/SDs/SDCalculateTotalPrice.pdf
  03 Design/SDs/SDCalculateTotalPrice.vsdx
  03 Design/SDs/SDCalculateWallPrice.pdf
  03 Design/SDs/SDCalculateWallPrice.vsdx
  03 Design/SDs/SDGetStores.pdf
  03 Design/SDs/SDGetStores.vsdx
  03 Design/SDs/SDSetCustomerAddress.pdf
  03 Design/SDs/SDSetCustomerAddress.vsdx
  03 Design/SDs/SDSetCustomerEmailAddress.pdf
  03 Design/SDs/SDSetCustomerEmailAddress.vsdx
  03 Design/SDs/SDSetCustomerName.pdf
  03 Design/SDs/SDSetCustomerName.vsdx
  03 Design/SDs/SDSetCustomerPhoneNumber.pdf
  03 Design/SDs/SDSetCustomerPhoneNumber.vsdx
  03 Design/SDs/SDSetCustomerZIPCode.pdf
  03 Design/SDs/SDSetCustomerZIPCode.vsdx
  03 Design/SDs/SDSetStore.pdf
  03 Design/SDs/SDSetStore.vsdx
  03 Design/SDs/SDSetWallHeight.pdf
  03 Design/SDs/SDSetWallHeight.vsdx
  03 Design/SDs/SDSetWallWidth.pdf
  03 Design/SDs/SDSetWallWidth.vsdx
  03 Design/SDs/SDnotifyObservers.pdf
  03 Design/SDs/SDnotifyObservers.vsdx
Labels: enhancement

#115 Create OCs for UC1
  03 Design/OCs/OCCalculateTotalPrice.md
  03 Design/OCs/OCCalculateWallPrice.md
  03 Design/OCs/OCGetStores.md
  03 Design/OCs/OCSendRequest.md
  03 Design/OCs/OCSetCustomerAddress.md
  03 Design/OCs/OCSetCustomerEmailAddress.md
  03 Design/OCs/OCSetCustomerName.md
  03 Design/OCs/OCSetCustomerPhoneNumber.md
  03 Design/OCs/OCSetCustomerZIPCode.md
  03 Design/OCs/OCSetStore.md
  03 Design/OCs/OCSetWallHeight.md
  03 Design/OCs/OCSetWallWidth.md
Labels: documentation

#130 Updated createDCDforUseCase1 from master
  03 Design/OCs/OCCalculateTotalPrice.md
  03 Design/OCs/OCCalculateWallPrice.md
  03 Design/OCs/OCGetStores.md
  03 Design/OCs/OCSendRequest.md
  03 Design/OCs/OCSetCustomerAddress.md
  03 Design/OCs/OCSetCustomerEmailAddress.md
  03 Design/OCs/OCSetCustomerName.md
  03 Design/OCs/OCSetCustomerPhoneNumber.md
  03 Design/OCs/OCSetCustomerZIPCode.md
  03 Design/OCs/OCSetStore.md
  03 Design/OCs/OCSetWallHeight.md
  03 Design/OCs/OCSetWallWidth.md
Labels: documentation, enhancement

#137 Update createCustomerInformationScreen from createFirstLayoutScreen
  04 Implementation/.idea/misc.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/new_yorker_icon.png
Labels: documentation

#140 Create second layout screen
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/MainActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/values/strings.xml
Labels: enhancement

#143 Create customer information screen
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/res/values/strings.xml
Labels: enhancement

#125 Adding the initial DCD
  03 Design/DCDMainScenario.pdf
  03 Design/DCDMainScenario.vsdx
Labels: documentation

#121 Update Project Plan
  08 Project Management/ProjectPlan.md
Labels: documentation

#145 Updated createPreviewOrderLayout from master
  03 Design/DCDMainScenario.pdf
  03 Design/DCDMainScenario.vsdx
  08 Project Management/ProjectPlan.md
Labels: enhancement

#146 Create preview order layout
  04 Implementation/app/src/main/AndroidManifest.xml
  04 Implementation/app/src/main/java/com/example/newyorker/CustomizeOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/PreviewOrderActivity.java
  04 Implementation/app/src/main/java/com/example/newyorker/SendRequestActivity.java
  04 Implementation/app/src/main/res/layout-v21/activity__send__request.xml
  04 Implementation/app/src/main/res/layout-v21/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout-v21/activity_main.xml
  04 Implementation/app/src/main/res/layout-v21/activity_preview_order.xml
  04 Implementation/app/src/main/res/layout/activity__send__request.xml
  04 Implementation/app/src/main/res/layout/activity_customize_order.xml
  04 Implementation/app/src/main/res/layout/activity_main.xml
  04 Implementation/app/src/main/res/layout/activity_preview_order.xml
  04 Implementation/app/src/main/res/mipmap-xxxhdpi/preview_sample.png
  04 Implementation/app/src/main/res/values/colors.xml
  04 Implementation/app/src/main/res/values/strings.xml
Labels: enhancement

#148 UpdatedDCDRemovedDuplicateExceptions
  03 Design/DCDMainScenario.pdf
  03 Design/DCDMainScenario.vsdx
Labels: documentation
